### ISSUE TITLE
Error when using RL_fetch() and input ids don't match those in current RL version

### ISSUE THREAD

**Issue by andyarnell** [matthewlewis896/NatureMapRedList#10]
Multiple errors pop up.
First error, presumably for those that don't match with the RL version, happens for each missing match an starts:
"error calling combine function:
<simpleError in rbind(deparse.level,...): numbers of columns of arguments do not match>"

Second error then triggered at the end stops the creation of a new DF.
"Error in do.call ("cbind", ret): second argument must be a list"

This is mostly a problem for when rerunning analyses using input species Id lists from old redlist versions.

**Comment by matthewlewis896** [comment]
Issue seems to occur every 99 or so species. Possibly an API time out?

**Comment by matthewlewis896** [comment]
Bug was related to API limiting every 99 calls. Have implemented a solution which runs queries in batches of 99 and merges them. This seems to work.
